name: Python Linting
on: [pull_request]
permissions:
  checks: write
  contents: write
jobs:
  PythonLinting:
    name: Python linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install autopep8 flake8
      - name: Lint Action
        uses: wearerequired/lint-action@v2.1.0
        with:
          auto_fix: true
          autopep8: true
          autopep8_dir: blazar_proxy/
          autopep8_auto_fix: true
          flake8: true
          flake8_dir: blazar_proxy/
          neutral_check_on_warning: true